server:
  port: 8080

spring:
  application:
    name: aviation-data-gateway
  main:
    banner-mode: "console"
  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: ALWAYS

aviation:
  api:
    base-url: https://api.aviationapi.com/v1
    timeout:
      connect-ms: 2000
      read-ms: 3000

resilience4j:
  circuitbreaker:
    instances:
      aviationApi:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

#  retry:
#    instances:
#      aviationApi:
#        maxAttempts: 3
#        waitDuration: 200ms
